### ISSUE TITLE
[bug] NOT NULL constraint failed: django_loci_floorplan.floor

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-loci#65]
```
IntegrityError at /admin/testdeviceapp/device/add/
NOT NULL constraint failed: django_loci_floorplan.floor
```

Steps to reproduce:
1. Create a device with new indoor environment, **flag it as mobile**
2. In the "Indoor coordinates" section, do not fill  a value for `floor`.
3. Complete the rest of the form correctly.
4. Submit

![](https://files.gitter.im/59108303d73408ce4f5de0c9/3wnq/sample1.png)

**Comment by nemesisdesign** [comment]
I cannot replicate this issue in django-loci, trying on master.

When I create a device with type indoor and supply no floorplan information, the browser asks for confirmation that I want to save an indoor device without supplying indoor coordinates, I confirm that and the device gets saved without issues, which is OK, because sometimes people need to create objects, flag them as indoor but they can't set the indoor coordinates in that moment, they defer that for the future, we recently changed the code to allow this.

So what is the issue? @Purhan were you able to replicate this issue in the dev environment? Were you able to write a failing test to replicate the issue? That's what we have to do before trying to fix something.

@atb00ker can you replicate this issue on the current master after running all the migrations?

**Comment by Purhan** [comment]
> So what is the issue? @Purhan were you able to replicate this issue in the dev environment?

Yes, I was able to replicate the issue for the exact settings as in the screenshot. I have pushed a patch in the commit above.

**Comment by atb00ker** [comment]
@nemesisdesign  Yes, I am able to do it in latest master, here is a screen recording: https://streamable.com/i9s6v1

**Comment by nemesisdesign** [comment]
Thank you very much @atb00ker, now is a lot clearer, the info of flagging it as mobile was missing from the issue description (I added it now), that's why I was not able to replicate it. I now remember that you wrote this in the general chat, but I forgot, so remember to always update the issue description when you find out that some key info is missing, otherwise we risk that multiple people will incur in the same issue repeatedly.

So, based on what I can see, the solution is clear, in this case a a ValidationError should be raised, while it's not being raised and then the saving fails on the DB side because the field is NOT NULL (rightly so).
